### ISSUE TITLE
Snake Eye chance to force an 11 roll is incorrect.

### ISSUE THREAD

**Issue by almuth150** [topaz-next/topaz#2295]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
The bonus chance for forcing a roll to total 11 should be 10% per merit past the first one (max 40% from merits). However, it's currently set to 5% per merit (max 20%) in the merits.sql table.

https://www.bg-wiki.com/bg/Snake_Eye

**Comment by wrenffxi** [comment]
The history here is that when the 2020-05-16 update dropped, Square Enix released two sets of dev notes that didn't agree with each other.

The [Japanese dev notes](https://forum.square-enix.com/ffxi/threads/23294) and the in-game descriptions in both languages, agree that it's +10%/merit after the first: 

![image](https://user-images.githubusercontent.com/21246949/103245825-62836180-492f-11eb-8418-27ddf0821458.png)
![image](https://user-images.githubusercontent.com/21246949/103245853-7d55d600-492f-11eb-8b4b-063db6fa7840.png)

But the [English dev notes](https://forum.square-enix.com/ffxi/threads/23295) say it's +5%/merit after the first:

![image](https://user-images.githubusercontent.com/21246949/103245895-96f71d80-492f-11eb-8c5d-d0185e398dff.png)

[FFXIclopedia assumed](https://ffxiclopedia.fandom.com/wiki/Snake_Eye) the 5% in the English dev notes was correct, and that the in-game description was typoed.

[BG FFXI Wiki assumed](https://www.bg-wiki.com/bg/Snake_Eye) the 10% is correct, and that the English dev notes were in error.

I'm inclined to believe that 10% is correct, because three out of four sources from SE agree.  Will fix shortly.
