### ISSUE TITLE
Missing key item obtained text during The Jester Who'd Be King

### ISSUE THREAD

**Issue by Era-Lusiphur** [topaz-next/topaz#2312]
During Windurst mission 8-2, The Jester Who'd Be King, Tosuka-Porika gives the player the KI Optistery Ring, but there is no accompanying text confirming it like the other NPCs in the quest. This is a minor issue that may result in some confusion for players. 

**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by wrenffxi** [comment]
From what I see in the code, this is happening because the player already has this key item.

The player acquires the Opistery Ring during [Windurst 7-1: The Sixth Ministry](https://ffxiclopedia.fandom.com/wiki/The_Sixth_Ministry#Walkthrough) and we never remove the key item during that mission.  So when they reach 8-2, they've still got it.

The walkthrough for 7-1 mentions that the Opistery Ring is a temporary KI, but it doesn't mention which step removes it from the player.  I watched Wiggo's excellent capture of this mission, and believe the Opistery Ring KI is removed when the player returns to Tosuka-Porika and receives the Blank Book of the Gods.

I'll PR a fix shortly.

**Comment by Era-Lusiphur** [comment]
Good catch! I wasn't sure if this would be deemed PRable currently, so just put a pin in it as an issue and didn't bother looking at the scripts. Been running through Windy missions on Canaria and noted a few things to fix later (some missing optional mission dialogue referred to on wikipedia, etc).
