### ISSUE TITLE
[sol_refactor] GM command !hp non functional

### ISSUE THREAD

**Issue by Omnione** [topaz-next/topaz#2372]
**_I have:_**

- [x] searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

**action to reproduce:**  GM command !hp
**file:**  hp.lua
**error:**   [Error] cmdhandler::call: (hp) error: scripts/commands/hp.lua:23: attempt to index field 'tpz' (a nil value)

**Comment by wrenffxi** [comment]
I could not replicate this on current sol_refactor branch.

So it's not an issue with the command itself; but maybe some other action caused the tpz table to be wiped (which of course would be a totally game-breaking state, since everything uses this table)

**Comment by ghost** [comment]
Looks like bad search and replace after checking that file out: targ = tpz.core.tpz.core.getPlayerByName(target)

Fix incoming

**Comment by wrenffxi** [comment]
LOL I swear I looked right at that twice and didn't notice the duplication.  I didn't replicate the issue because I always used the command with something targeted, and never passed in name.  One question: I notice all the other command scripts use tpz.core.getPlayerByName rather than GetPlayerByName.  I remember reading somewhere that these are synonymous, I think?  Do we have a preference for one or the other?

**Comment by ghost** [comment]
To be honest, I prefer the pascal case indicating its a global function, but have no problem either way.  With the way the bindings are configured either tpz.core.lowerCaseFunction() will work, or UpperCaseFunction().

Originally, I believe this was searched-replaced-added on, because the C++ function name was camel-cased instead of Pascal.

**Comment by zach2good** [comment]
I'm still not sure if `tpz.core.func(x)` is useful at all 😆

**Comment by ghost** [comment]
I wouldn't say its not useful, but I would urge consistency across the board (and that wouldn't be a fun update).

**Comment by zach2good** [comment]
I ended up reverting all the tpz.core bindings to their original form 💀 

This issue was closed with: https://github.com/topaz-next/topaz/pull/2389
