### ISSUE TITLE
[canary] Eagle eye shot  damage

### ISSUE THREAD

**Issue by Chronos77** [topaz-next/topaz#2523]
- [ x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [ x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ x] This issue occurs on `canary` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
![image](https://user-images.githubusercontent.com/1618002/106306243-0ed1a400-625e-11eb-9a12-e0eb19873ca0.png)
![image](https://user-images.githubusercontent.com/1618002/106306278-1c872980-625e-11eb-924c-7621d5d02f04.png)

**Comment by TeoTwawki** [comment]
Hey there Chronos77, just want to let you know that you don't want both the space and the X inside the square brackets on issues, you can actually save the post without filling them in, and it becomes a clickable box you click with your mouse after!

```md
<!-- remove space and place 'x' mark between square [] brackets or click the checkbox after saving to affirm: -->
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
```

- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [ ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ ] This issue occurs on `release` branch (if other branch, please specify)

Like so

(P.s.they will only be clickable by the original poster, so I can't click yours on/off and you can't click mine)

**Comment by Chronos77** [comment]
thanks  @TeoTwawki @claywar,  I'm not doing as much with Eagle Eye Shots yet, but it's fixed! lol
